import asyncio
from app.models.workflow import Workflow

async def generate_scripts(workflow: Workflow) -> Workflow:
    """
    Returns a Workflow object with a list of LLM Scripts
    """
    await asyncio.sleep(0)  
    lines = [
        f"**Product Name:** {workflow.product.product_name}",
        "",
        f"**Description:**\n{workflow.product.product_description}",
        "",
        "This is a list of scripts generated by the LLM"
    ]
    
    return workflow.copy(update={"llm_scripts": lines})

